<div class="container">
    <h5 style="    margin: 42px 0;
    text-align: center;
    font-size: 44px;
    text-transform: UPPERCASE;
    font-weight: 600;
    color: #828282;
    margin-bottom: 0px;"><?php _lang('cryptocurrency-converter')?></h5>
</div>

<div class="pane " style="margin-top: 70px;
    margin-bottom: 250px;">
    <div class="container">
        <?php echo view('main::home/calculator')?>
    </div>
</div>