<script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>
  
  <script src="https://code.highcharts.com/highcharts.js"></script>

<script type="text/javascript">
	$(function(){
		
		$("#load").load('/test/public_html/app/views/coin/index1.htm')
	});
		
	</script>

<div id="coin-chart" class="coin-chart">

    
    <div id="load"></div> 
    <!--- <div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>-->
</div>