<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <div class="pane bg-white">
            <div class="row">
                <div class="col-md-4">
                    <img style="width: 100%;margin-top: 20px" src="<?php echo url('public/assets/images/access.png')?>"/>
                </div>
                <div class="col-md-8">
                    <h5 style="margin: 15px 0"><?php _lang('premium-access-only')?></h5>
                    <p>
                        <a href="<?php echo url('portfolio')?>"><strong><?php _lang('portfolio')?></strong></a> <?php _lang('portfolio-welcome-note')?>
                    </p>

                    <p>
                        <a href="<?php echo url('alert')?>"><strong><?php _lang('alerts')?></strong></a> <?php _lang('alerts-welcome-note')?>
                    </p>

                    <p>
                        <a href="<?php echo url('watchlist')?>"><strong><?php _lang('watchlist')?></strong></a> <?php _lang('watchlist-welcome-note')?>
                    </p>

                    <a href="<?php echo url('pricing')?>" class="btn btn-sm btn-block btn-primary ajax-link"><?php _lang('see-pricing')?></a>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-3"></div>
</div>