<div class="container">
    <h5 style="margin: 25px 0"><?php _lang('account-settings')?></h5>
</div>
<div class="pane">
    <form action="" method="post">
        <div class="container">
            <?php if($error):?>
                <div class="alert alert-danger"><?php echo $error?></div>
            <?php endif?>
            <?php if($message):?>
                <div class="alert alert-success"><?php echo $message?></div>
            <?php endif?>
            <div class="row">
                <div class="col-md-6">
                    <?php if(config('enable-subscription', false)):?>
                        <div class="pane bg-white">
                            <div style="margin: 15px 0;font-size: 20px">
                                <strong><?php _lang('subscription-plan')?> : </strong>
                                <?php echo get_user_plan()?>
                            </div>

                            <div style="margin: 15px 0">
                                <strong><?php _lang('valid-till')?> : </strong>
                                <?php echo get_user_plan_time()?>

                                <?php $user = get_user(); if(!subscription_active() or $user['subscription_plan'] == 0):?>
                                    <a href="<?php echo url('pricing')?>" class="ajax-link btn btn-lg btn-outline-warning"><?php _lang('upgrade-now')?></a>
                                <?php endif?>
                            </div>

                            <div class="pane " style="color: grey">
                                <?php _lang('subscription-note')?>
                            </div>
                        </div>
                    <?php endif?>
                    <div class="pane bg-white">
                        <div class="form-group row">
                            <label class="label col-sm-4"><?php _lang('email-address')?></label>
                            <input type="email" class="form-control col-sm-6" name="email" value="<?php echo get_user()['email']?>"/>
                        </div>

                        <div  style="padding: 10px; text-align: center">
                            <button class="btn btn-primary btn-sm"><?php _lang('save')?></button>
                        </div>
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="pane bg-white">
                        <div class="form-group row">
                            <label class="label col-sm-4"><?php _lang('old-password')?></label>
                            <input type="password" class="form-control col-sm-6" name="old" />
                        </div>

                        <div class="form-group row">
                            <label class="label col-sm-4"><?php _lang('new-password')?></label>
                            <input type="password" class="form-control col-sm-6" name="new" />
                        </div>

                        <div class="form-group row">
                            <label class="label col-sm-4"><?php _lang('confirm-new-password')?></label>
                            <input type="password" class="form-control col-sm-6" name="confirm" />
                        </div>

                        <hr/>

                        <div  style="padding: 10px; text-align: center">
                            <button type="submit" class="btn btn-primary btn-sm"><?php _lang('change-password')?></button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>