<ul class="list-unstyled">
    <?php foreach($news as $new):?>
        <li class="media">
            <img style="width: 130px" class="d-flex mr-3" src="<?php echo $new['imageurl']?>" alt="">
            <div class="media-body">
                <h5 class="mt-0 mb-1">
                    <a href="javascript:void(0)" onclick="window.open('<?php echo $new['url']?>')"><?php echo $new['title']?></a>
                    <span style="color: grey;font-size: 9px"><?php echo format_time($new['published_on'])?></span>
                </h5>
                <?php echo str_limit($new['body'], 250)?>

                <div class="info">
                     <span class="badge badge-info" style="padding: 5px 7px;margin: 7px 0"><?php echo $new['source']?></span>
                    <?php foreach(explode('|', $new['tags']) as $tag):?>
                        <span class="badge badge-default" style="padding: 5px 7px;margin: 7px 0"><?php echo $tag?></span>
                    <?php endforeach?>
                </div>
            </div>
        </li>
    <?php endforeach?>
</ul>