<div class="clearfix">
    <div class="float-left">
        <h5><?php _lang('modules-manager')?></h5>
    </div>
</div>
<table class="table table-hover table-striped">
    <thead>
    <tr>
        <th></th>
        <th style="width: 70%"><a > <?php _lang('Module')?> </a></th>
        <th style="width: 20%"><a ><?php _lang('action')?></a></th>

    </tr>
    </thead>
    <tbody>
        <?php $modules = app()->listModules();?>
        <?php foreach($modules as $module=>$info):?>
            <tr>
                <td>
                    <div style="border-radius:100px;color:white;width: 40px;height:40px;font-size: 20px;background: #99FF00;text-align: center;padding:4px 10px;display: inline-block">
                        <?php
                        $name = substr($module, 0, 1);
                        echo ucwords($name);
                        ?>
                    </div>
                </td>
                <td>
                    <div style="display: inline-block">
                        <h5><?php echo $info['title']?> <span style="font-size: 12px;color: grey"><?php _lang('by')?> <?php echo $info['author']?></span></h5>
                        <p><?php echo $info['description']?></p>
                        <p><?php _lang('version')?> : <strong> <?php echo $info['version']?></strong></p>
                    </div>
                </td>
                <td>
                    <?php if(app()->moduleIsEnabled($module)):?>
                            <a href="<?php echo url('admincp/module?action=disable&module='.$module)?>" class="btn btn-sm btn-danger"><?php _lang('disable')?></a>
                    <?php else:?>
                        <a href="<?php echo url('admincp/module?action=enable&module='.$module)?>" class="btn btn-sm btn-secondary"><?php _lang('enable')?></a>
                    <?php endif?>
                </td>
            </tr>
        <?php endforeach?>
    </tbody>

</table>

<?php if(!$modules):?>
    <div class="" style="text-align: center;margin: 20px">
        <?php _lang('no-module-found')?>
    </div>
<?php endif?>