




<?php if(!subscription_active(null, 'alerts')):?>
    <div class="container">
        <h5 style="margin: 30px 0;text-align: center"><?php _lang('price-alerts')?></h5>
        <div style="margin-bottom: 15px;text-align: center">

        </div>
    </div>
    <div class="pane">
        <?php echo view('main::user/access')?>
    </div>
<?php else:?>
    <div class="container">
        <h5 style="margin: 42px 0;text-align: center;font-size: 44px;text-transform:  UPPERCASE;font-weight: 600;color: #828282;margin-bottom: 0px;"><?php _lang('price-alerts')?></h5>
        <div style="margin-bottom: 15px;text-align: center">

        </div>
    </div>
	<div class="container">
    <div class="pane">
        <div class="row">
		
		
		<div class="col-md-12">
                <div class="pane bg-white">
                    <h5 style="text-align:center;margin-bottom: 26px;"><?php _lang('add-alert')?></h5>

                    <form id="alert-form" action="" method="post">
                        <select name="coin" required style="width: 100% !important;" class="select2 form-control" >
                            <?php foreach(get_all_coins() as $dcoin):?>
                                <option <?php echo ($dcoin['symbol'] == 'BTC') ? 'selected' : null?> value="<?php echo $dcoin['symbol']?>">
                                    <?php echo $dcoin['name']?> [<?php echo $dcoin['symbol']?>]
                                </option>
                            <?php endforeach?>
                        </select>

                        <div class="row" style="margin-top:20px;margin-bottom: 32px">
                            <div class="col-md-6" style="    margin-bottom: 10px;">
                                <select name="type" class="form-control">
                                    <option value="1"><?php _lang('rise-above')?></option>
                                    <option value="2"><?php _lang('fall-below')?></option>
                                </select>
                            </div>
                            <div class="col-md-6" style="    margin-bottom: 10px;">
                                <input style="    height: calc(2.25rem + 2px);" type="text" name="price" class="form-control" />
                            </div>
                        </div>

                        <button style="    display: block;
    margin: 0 auto;
    width: 104px;" class="btn btn-sm btn-primary"><?php _lang('save')?></button>
                    </form>

                    <hr style="    margin-top: 34px;" />
                    <h6 style="text-align:center;margin-top: 24px;"><?php _lang('email-notification')?></h6>
                    <p style="text-align: center;
    margin: 0px;"><?php _lang('email-notification-note')?></p>
                </div>
            </div>
		
		
		
		
            <div class="col-md-12">
                <div class="pane">
                    <table id="portfolioTransactionList" class="table table-hover  table-coin table-coin-res">
                        <thead>
                        <tr>
                            <th  style="
    text-align:  center;
"><?php _lang('coin')?></th>
                            <th  style="
    text-align:  center;
"><?php _lang('current-price')?></th>
                            <th  style="
    text-align:  center;
"><?php _lang('alert-type')?></th>
                            <th  style="
    text-align:  center;
"><?php _lang('notified')?></th>
                            <th  style="
    text-align:  center;
"><?php _lang('action')?></th>
                        </tr>
                        </thead>
                        <tbody>
                            <?php foreach(get_alerts() as $alert):$coin = get_coin($alert['coin'])?>
                                <tr data-price="<?php echo format_coin_price($coin['price'],false,false)?>" class="coin-detail-container <?php echo $coin['symbol']?>-detail-container" id="" data-symbol="<?php echo $coin['symbol']?>">
                                    <td  style="
    text-align:  center;
" class="clearfix">
                                        <div class="name"><?php _lang('coin')?></div>
                                        <div class="info">
                                            <a href="<?php echo coin_link($coin)?>" class="ajax-link" >
                                                <img class="coin-list-logo" src="<?php echo get_coin_logo($coin)?>" style=""/>
                                                <?php echo $coin['name']?>
                                            </a>
                                        </div>
                                    </td>
                                    <td  style="
    text-align:  center;
" class="clearfix">
                                        <div class="name"><?php _lang('current-price')?></div>
                                       <div class="info">
                                           <?php $currency = find_currency($alert['alert_currency'])?>
                                           <?php echo getCurrencySymbol()?>
                                           <span class="price" data-value="<?php echo $coin['price']?>"><?php

if(number_format(format_coin_price($coin['price'],false,false),2,".",",") >= 1000){
		
		echo number_format(format_coin_price($coin['price'],false,false),2,".",",");
		
	} else if (number_format(format_coin_price($coin['price'],false,false),2,".",",") >= 1)  {
		
		echo number_format(format_coin_price($coin['price'],false,false),2,".",",");
		
	}  else if (number_format(format_coin_price($coin['price'],false,false),2,".",",") == 0)  {
		
		echo number_format(format_coin_price($coin['price'],false,false),2,".",",");
		
	} else {
		
		echo number_format(format_coin_price($coin['price'],false,false),6,".",",");
		
	}


										   ?></span>
                                       </div>
                                    </td>
                                    <td  style="
    text-align:  center;
" class="clearfix">
                                        <div class="name"><?php _lang('alert-type')?></div>
                                        <div class="info">
                                            <span class="badge badge-default" style="padding:7px 5px;     background-color: <?php if ($alert['alert_type'] == 1){ echo '#3ea54b'; } else { echo '#a53e3e'; }?>; "><?php echo ($alert['alert_type'] == 1) ? lang('rise-above') : lang('fall-below')?></span>
                                            <div style="margin-top: 5px">
                                                <span class="pricedd"><?php echo getCurrencySymbol()?><?php

if(number_format(format_coin_price($alert['alert_value'],false,false),2,".",",") >= 1000){
		
		echo number_format(format_coin_price($alert['alert_value'],false,false),2,".",",");
		
	} else if (number_format(format_coin_price($alert['alert_value'],false,false),2,".",",") >= 1)  {
		
		echo number_format(format_coin_price($alert['alert_value'],false,false),2,".",",");
		
	}  else if (number_format(format_coin_price($alert['alert_value'],false,false),2,".",",") == 0)  {
		
		echo number_format(format_coin_price($alert['alert_value'],false,false),2,".",",");
		
	} else {
		
		echo number_format(format_coin_price($alert['alert_value'],false,false),6,".",",");
		
	}


										   ?></span>
                                            </div>
                                        </div>
                                    </td>
                                    <td  style="
    text-align:  center;
" class="clearfix">
                                        <div class="name"><?php _lang('notified')?></div>
                                        <div class="info">
                                            <span class="badge badge-default" style="padding:7px 5px "><?php echo ($alert['notify']) ? lang('yes') : lang('no')?></span>
                                        </div>
                                    </td>
                                    <td  style="
    text-align:  center;
" class="clearfix">
                                        <div class="name"><?php _lang('action')?></div>
                                        <div class="info">
                                            <a href="<?php echo url('alerts')?>?action=delete&id=<?php echo $alert['id']?>" class="btn btn-sm btn-secondary"><i class="icons icon-trash"></i></a>
                                        </div>
                                    </td>
                                </tr>
                            <?php endforeach?>
                        </tbody>

                        </table>
                </div>
            </div>
           </div> 
        </div>
		
		<?php if(config('top_ads', false)):?>

            <div class="" style="padding: 10px 0;    margin-bottom: 30px; ">
                <?php echo config('top_ads', '')?>
            </div>
			
        <?php endif?>
		
    </div>
<?php endif?>