<?php if(!subscription_active(null, 'roi-calculator')):?>
    <div class="container">
        <h5 style="margin: 30px 0;text-align: center"><?php _lang('roi-calculator')?></h5>
        <div style="margin-bottom: 15px;text-align: center">

        </div>
    </div>
    <div class="pane">
        <?php echo view('main::user/access')?>
    </div>
<?php else:?>
    <div class="container">
        <h5 style="margin: 42px 0;
    text-align: center;
    font-size: 44px;
    text-transform: UPPERCASE;
    font-weight: 600;
    color: #828282;
    margin-bottom: 0px;"><?php _lang('roi-calculator')?></h5>
        <div style="margin-bottom: 15px;text-align: center">

        </div>
    </div>
    <div class="pane">
        <div class="container">
            <div class="" style="font-size: 30px;padding: 160px 20px;text-align: center">

                <?php if(isset($answers) and $answers): $coinDetail = get_coin(input('coin'))?>
                    <p>
                        <?php _lang('roi-answer', array(
                            'amount' => $answers['amount'],
                            'time' => $answers['time'],
                            'percent' => $answers['percent'],
                            'profit' => $answers['profit'],
                            'name' => $coinDetail['name']
                        ))?>
                    </p>

                    <a href="<?php echo url('roi')?>" class="btnn btn-lg btn-primary ajax-link"><?php _lang('calculate-again')?></a>
                <?php else:?>
                    <form action="" method="post">
                        <p>
                            <?php _lang('what-if-invest')?> <?php echo getCurrencySymbol()?><input placeholder="<?php _lang('enter-amount')?>" style="    margin-left: 14px;
    top: -7px;position:relative;bottom:10px;padding:5px 10px;height: 36px;border: solid 1px #DDDCDC;border-radius: 10px" type="text" name="amount"/> <?php _lang('in')?>
                            <select style="padding:0px 10px;height: 35px;border: solid 1px #DDDCDC;border-radius: 10px;width: 200px"  name="coin" class="" onchange="return switch_roi_currency(this)" >
                                <?php foreach(get_all_coins() as $dcoin):?>
                                    <option <?php echo ($dcoin['symbol'] == $coin) ? 'selected' : null?> value="<?php echo $dcoin['symbol']?>"><?php echo $dcoin['name']?></option>
                                <?php endforeach?>
                            </select>
                            <?php _lang('on')?>
                            <select style="padding:0px 10px;height: 35px;border: solid 1px #DDDCDC;border-radius: 10px" name="day">
                                <?php for($i=1;$i<=31;$i++):?>
                                    <option value="<?php echo $i?>"><?php echo $i?></option>
                                <?php endfor?>
                            </select>
                            <select style="padding:0px 10px;height: 35px;border: solid 1px #DDDCDC;border-radius: 10px" name="month">
                                <?php foreach(getMonths() as $id => $name):?>
                                    <option value="<?php echo $id?>"><?php echo $name?></option>
                                <?php endforeach?>
                            </select>

                            <select style="padding:0px 10px;height: 35px;border: solid 1px #DDDCDC;border-radius: 10px" name="year">
                                <?php for($i=2011;$i<=date('Y');$i++):?>
                                    <option value="<?php echo $i?>"><?php echo $i?></option>
                                <?php endfor?>
                            </select>
                        </p>

                        <button type="submit" class="btnn btn-sm btn-primary"><?php _lang('calculate')?></button>

                    </form>
                <?php endif?>
            </div>
			
			
			
			

        </div>
    </div>
<?php endif?>

